In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/house_prices.csv')
data

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,N,0,...,7,1180.0,0.0,1955,0,98178,47.5112,-122.257,1340.0,5650.0
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,N,0,...,7,2170.0,400.0,1951,1991,98125,47.7210,-122.319,1690.0,7639.0
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,N,0,...,6,770.0,0.0,1933,0,98028,47.7379,-122.233,2720.0,8062.0
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,N,0,...,7,1050.0,910.0,1965,0,98136,47.5208,-122.393,1360.0,5000.0
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,N,0,...,8,1680.0,0.0,1987,0,98074,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,N,0,...,8,1530.0,0.0,2009,0,98103,47.6993,-122.346,1530.0,1509.0
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,N,0,...,8,NaN,0.0,2014,0,98146,47.5107,-122.362,1830.0,7200.0
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,N,0,...,7,1020.0,0.0,2009,0,98144,47.5944,-122.299,1020.0,2007.0
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,N,0,...,8,1600.0,0.0,2004,0,98027,47.5345,-122.069,1410.0,1287.0
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,N,0,...,7,1020.0,0.0,2008,0,98144,47.5941,-122.299,1020.0,1357.0

In [ ]:
features = data.iloc[:,3:21]
features

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,N,0,Average,7,1180.0,0.0,1955,0,98178,47.5112,-122.257,1340.0,5650.0
1,3,2.25,2570,7242,2.0,N,0,Average,7,2170.0,400.0,1951,1991,98125,47.7210,-122.319,1690.0,7639.0
2,2,1.00,770,10000,1.0,N,0,Average,6,770.0,0.0,1933,0,98028,47.7379,-122.233,2720.0,8062.0
3,4,3.00,1960,5000,1.0,N,0,Very Good,7,1050.0,910.0,1965,0,98136,47.5208,-122.393,1360.0,5000.0
4,3,2.00,1680,8080,1.0,N,0,Average,8,1680.0,0.0,1987,0,98074,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,3,2.50,1530,1131,3.0,N,0,Average,8,1530.0,0.0,2009,0,98103,47.6993,-122.346,1530.0,1509.0
21609,4,2.50,2310,5813,2.0,N,0,Average,8,NaN,0.0,2014,0,98146,47.5107,-122.362,1830.0,7200.0
21610,2,0.75,1020,1350,2.0,N,0,Average,7,1020.0,0.0,2009,0,98144,47.5944,-122.299,1020.0,2007.0
21611,3,2.50,1600,2388,2.0,N,0,Average,8,1600.0,0.0,2004,0,98027,47.5345,-122.069,1410.0,1287.0
21612,2,0.75,1020,1076,2.0,N,0,Average,7,1020.0,0.0,2008,0,98144,47.5941,-122.299,1020.0,1357.0

In [ ]:
label = data.iloc[:,2:3]
label

        price
0      221900
1      538000
2      180000
3      604000
4      510000
...       ...
21608  360000
21609  400000
21610  402101
21611  400000
21612  325000

[21613 rows x 1 columns]

In [ ]:
data.shape

(21613, 21)

In [ ]:
data = data.dropna()
data

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,N,0,...,7,1180.0,0.0,1955,0,98178,47.5112,-122.257,1340.0,5650.0
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,N,0,...,7,2170.0,400.0,1951,1991,98125,47.7210,-122.319,1690.0,7639.0
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,N,0,...,6,770.0,0.0,1933,0,98028,47.7379,-122.233,2720.0,8062.0
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,N,0,...,7,1050.0,910.0,1965,0,98136,47.5208,-122.393,1360.0,5000.0
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,N,0,...,8,1680.0,0.0,1987,0,98074,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21607,2997800021,20150219T000000,475000,3,2.50,1310,1294,2.0,N,0,...,8,1180.0,130.0,2008,0,98116,47.5773,-122.409,1330.0,1265.0
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,N,0,...,8,1530.0,0.0,2009,0,98103,47.6993,-122.346,1530.0,1509.0
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,N,0,...,7,1020.0,0.0,2009,0,98144,47.5944,-122.299,1020.0,2007.0
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,N,0,...,8,1600.0,0.0,2004,0,98027,47.5345,-122.069,1410.0,1287.0
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,N,0,...,7,1020.0,0.0,2008,0,98144,47.5941,-122.299,1020.0,1357.0

In [ ]:
data.shape

(21608, 21)

In [ ]:
data = data.drop_duplicates()

In [ ]:
data.shape

(21608, 21)

In [ ]:
features = pd.get_dummies(features)
features

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,grade,sqft_above,sqft_basement,yr_built,...,long,sqft_living15,sqft_lot15,waterfront_N,waterfront_Y,condition_Average,condition_Fair,condition_Good,condition_Poor,condition_Very Good
0,3,1.00,1180,5650,1.0,0,7,1180.0,0.0,1955,...,-122.257,1340.0,5650.0,1,0,1,0,0,0,0
1,3,2.25,2570,7242,2.0,0,7,2170.0,400.0,1951,...,-122.319,1690.0,7639.0,1,0,1,0,0,0,0
2,2,1.00,770,10000,1.0,0,6,770.0,0.0,1933,...,-122.233,2720.0,8062.0,1,0,1,0,0,0,0
3,4,3.00,1960,5000,1.0,0,7,1050.0,910.0,1965,...,-122.393,1360.0,5000.0,1,0,0,0,0,0,1
4,3,2.00,1680,8080,1.0,0,8,1680.0,0.0,1987,...,-122.045,1800.0,7503.0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,3,2.50,1530,1131,3.0,0,8,1530.0,0.0,2009,...,-122.346,1530.0,1509.0,1,0,1,0,0,0,0
21609,4,2.50,2310,5813,2.0,0,8,NaN,0.0,2014,...,-122.362,1830.0,7200.0,1,0,1,0,0,0,0
21610,2,0.75,1020,1350,2.0,0,7,1020.0,0.0,2009,...,-122.299,1020.0,2007.0,1,0,1,0,0,0,0
21611,3,2.50,1600,2388,2.0,0,8,1600.0,0.0,2004,...,-122.069,1410.0,1287.0,1,0,1,0,0,0,0
21612,2,0.75,1020,1076,2.0,0,7,1020.0,0.0,2008,...,-122.299,1020.0,1357.0,1,0,1,0,0,0,0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
features = scaler.fit_transform(features)
features

array([[0.09090909, 0.125     , 0.06716981, ..., 0.        , 0.        ,
        0.        ],
       [0.09090909, 0.28125   , 0.17207547, ..., 0.        , 0.        ,
        0.        ],
       [0.06060606, 0.125     , 0.03622642, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06060606, 0.09375   , 0.05509434, ..., 0.        , 0.        ,
        0.        ],
       [0.09090909, 0.3125    , 0.09886792, ..., 0.        , 0.        ,
        0.        ],
       [0.06060606, 0.09375   , 0.05509434, ..., 0.        , 0.        ,
        0.        ]])